name: ChessBot CI (testing branch)

on:
  push:
    branches: [ testing_branch ]
  pull_request:
    branches: [ testing_branch ]
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build and Run (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Restore dependencies
        run: dotnet restore Chess-Challenge/Chess-Challenge.csproj

      - name: Build
        run: dotnet build Chess-Challenge/Chess-Challenge.csproj --configuration Release --no-restore

      - name: Run with virtual display
        working-directory: Chess-Challenge
        run: xvfb-run -a dotnet run -c CI

  check_output:
    needs: build-and-run
    name: cat test
    runs-on: ubuntu-latest

    steps:
      - name: find the file
        run: tree

      - name: find the file
        run: cat bot_match_results.txt


