name: ChessBot CI (testing branch)

on:
  push:
    branches: [ testing_branch ]
  pull_request:
    branches: [ testing_branch ]
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build and Run (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Chess-Challenge/Chess-Challenge.csproj

      - name: Build
        run: dotnet build Chess-Challenge/Chess-Challenge.csproj --configuration Release --no-restore

      - name: Run
        working-directory: Chess-Challenge
        run: dotnet run --configuration Release
